#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Dec 14th, 2014
# -----------------------------------------------------------------------------

VERSION=1.10.2
JAR=minecraft_server.${VERSION}.jar
MEMORY=`free -tm | grep Total | awk '{print int( $2*.75) }'`

if [ ! -f /data/$JAR ]
then
    curl "https://s3.amazonaws.com/Minecraft.Download/versions/${VERSION}/minecraft_server.${VERSION}.jar" -o /data/$JAR
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -Xmx${MEMORY}M -jar $JAR nogui

